# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  setup:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Node
        uses: actions/setup-node@v2
        with:
          node-version: '12'
          registry-url: 'https://registry.npmjs.org/'
      - name: Clear NPM Cache
        run: npm cache verify
      - name: Install NPM Dependencies
        run: npm ci
        
  build:
    needs: [setup]
    runs-on: windows-latest
  
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        run: npm run ci:build
  test:
    needs: [build]
    runs-on: windows-latest
  
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Test
        run: npm run ci:test
    
